# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmap.proto\x12\x12tibia.protobuf.map\x1a\x0cshared.proto\"\x98\x02\n\x03Map\x12\'\n\x05\x61reas\x18\x01 \x03(\x0b\x32\x18.tibia.protobuf.map.Area\x12%\n\x04npcs\x18\x02 \x03(\x0b\x32\x17.tibia.protobuf.map.Npc\x12\x33\n\x0eresource_files\x18\x03 \x03(\x0b\x32\x1b.tibia.protobuf.map.MapFile\x12\x43\n\x18top_left_tile_coordinate\x18\x04 \x01(\x0b\x32!.tibia.protobuf.shared.Coordinate\x12G\n\x1c\x62ottom_right_tile_coordinate\x18\x05 \x01(\x0b\x32!.tibia.protobuf.shared.Coordinate\"\xd2\x01\n\x04\x41rea\x12\x0f\n\x07\x61rea_id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x30\n\tarea_type\x18\x03 \x01(\x0e\x32\x1d.tibia.protobuf.map.AREA_TYPE\x12\x13\n\x0bsubarea_ids\x18\x04 \x03(\r\x12;\n\x10label_coordinate\x18\x05 \x01(\x0b\x32!.tibia.protobuf.shared.Coordinate\x12\x18\n\x10reject_donations\x18\x06 \x01(\x08\x12\r\n\x05\x61lias\x18\x07 \x01(\t\"c\n\x03Npc\x12\x0c\n\x04name\x18\x01 \x01(\t\x12:\n\x0ftile_coordinate\x18\x02 \x01(\x0b\x32!.tibia.protobuf.shared.Coordinate\x12\x12\n\nsubarea_id\x18\x03 \x01(\r\"\xe6\x01\n\x07MapFile\x12\x34\n\tfile_type\x18\x01 \x01(\x0e\x32!.tibia.protobuf.map.MAP_FILE_TYPE\x12>\n\x13top_left_coordinate\x18\x02 \x01(\x0b\x32!.tibia.protobuf.shared.Coordinate\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x14\n\x0c\x66ields_width\x18\x04 \x01(\r\x12\x15\n\rfields_height\x18\x05 \x01(\r\x12\x0f\n\x07\x61rea_id\x18\x06 \x01(\r\x12\x14\n\x0cscale_factor\x18\x07 \x01(\x01*b\n\rMAP_FILE_TYPE\x12\x19\n\x15MAP_FILE_TYPE_SUBAREA\x10\x00\x12\x1b\n\x17MAP_FILE_TYPE_SATELLITE\x10\x01\x12\x19\n\x15MAP_FILE_TYPE_MINIMAP\x10\x02*J\n\tAREA_TYPE\x12\x12\n\x0e\x41REA_TYPE_NONE\x10\x00\x12\x12\n\x0e\x41REA_TYPE_AREA\x10\x01\x12\x15\n\x11\x41REA_TYPE_SUBAREA\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAP_FILE_TYPE']._serialized_start=877
  _globals['_MAP_FILE_TYPE']._serialized_end=975
  _globals['_AREA_TYPE']._serialized_start=977
  _globals['_AREA_TYPE']._serialized_end=1051
  _globals['_MAP']._serialized_start=48
  _globals['_MAP']._serialized_end=328
  _globals['_AREA']._serialized_start=331
  _globals['_AREA']._serialized_end=541
  _globals['_NPC']._serialized_start=543
  _globals['_NPC']._serialized_end=642
  _globals['_MAPFILE']._serialized_start=645
  _globals['_MAPFILE']._serialized_end=875
# @@protoc_insertion_point(module_scope)
