# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: staticdata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'staticdata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10staticdata.proto\x12\x19tibia.protobuf.staticdata\"\x7f\n\nStaticData\x12\x33\n\x07monster\x18\x01 \x03(\x0b\x32\".tibia.protobuf.staticdata.Monster\x12<\n\x0c\x61\x63hievements\x18\x02 \x03(\x0b\x32&.tibia.protobuf.staticdata.Achievement\"\xa1\x01\n\x06Outfit\x12\x11\n\toutfit_id\x18\x01 \x01(\r\x12\x12\n\nhead_color\x18\x02 \x01(\r\x12\x13\n\x0btorso_color\x18\x03 \x01(\r\x12\x12\n\nlegs_color\x18\x04 \x01(\r\x12\x14\n\x0c\x64\x65tail_color\x18\x05 \x01(\r\x12\x0e\n\x06\x61\x64\x64ons\x18\x06 \x01(\r\x12!\n\x19object_appearance_type_id\x18\x07 \x01(\r\"X\n\x07Monster\x12\x0c\n\x04race\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x31\n\x06outfit\x18\x03 \x01(\x0b\x32!.tibia.protobuf.staticdata.Outfit\"W\n\x0b\x41\x63hievement\x12\x16\n\x0e\x61\x63hievement_id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05grade\x18\x04 \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'staticdata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATICDATA']._serialized_start=47
  _globals['_STATICDATA']._serialized_end=174
  _globals['_OUTFIT']._serialized_start=177
  _globals['_OUTFIT']._serialized_end=338
  _globals['_MONSTER']._serialized_start=340
  _globals['_MONSTER']._serialized_end=428
  _globals['_ACHIEVEMENT']._serialized_start=430
  _globals['_ACHIEVEMENT']._serialized_end=517
# @@protoc_insertion_point(module_scope)
